In [1]:
import numpy as np

In [18]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
!pip install numpy


In [8]:
import numpy as np

In [9]:
a=np.zeros(10)

In [10]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
a=np.ones(10)

In [12]:
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
a=np.ones(10)*5

In [14]:
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [16]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [28]:
np.random.randint(0,1,4)

array([0, 0, 0, 0])

In [30]:
np.random.rand(25).reshape(5,5)

array([[0.25777399, 0.74261047, 0.17186498, 0.22386561, 0.2163003 ],
       [0.1816491 , 0.49241508, 0.62058445, 0.97389148, 0.70907782],
       [0.23148322, 0.90167895, 0.60247167, 0.72390153, 0.96441337],
       [0.89961881, 0.09128227, 0.61800208, 0.91433887, 0.17321985],
       [0.74154942, 0.78524093, 0.57850661, 0.34888715, 0.46405031]])

In [31]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [32]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [35]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [37]:
mat[3:4,4:]

array([[20]])

In [39]:
mat[0:5,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [40]:
mat[4:,0:5]

array([[21, 22, 23, 24, 25]])

In [41]:
mat[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])